<?php
/**
 * 节假日分2种：
 *        普通节日：    不放假
 *        假日：        放假
 *
 * 节假日配置
 *    array(
 *        'time'        =>'时间',
 *        'name'        =>'名称',
 *        'days'        =>'放假天数',
 *        'start_year'=>'起始年',
 *        'work'        =>'是否需要工作',
 *    )
 *
 * @author zhusaidong [zhusaidong@gmail.com]
 */

const WORK     = 1;//工作，不放假
const NOT_WORK = 2;//不工作，放假

//阳历节日
$gregorian_holiday = [
	[
		'time'       => '1-1',
		'name'       => '元旦',
		'days'       => 1,
		'start_year' => 1949,
		'work'       => NOT_WORK,
	],
	//根据百度百科资料，国际劳动节起始于1890年，而中国劳动节起始于1949年
	[
		'time'       => '5-1',
		'name'       => '劳动节',
		'days'       => 1,
		'start_year' => 1949,
		'work'       => NOT_WORK,
	],
	[
		'time'       => '10-1',
		'name'       => '国庆节',
		'days'       => 7,
		'start_year' => 1949,
		'work'       => NOT_WORK,
	],
	[
		'time'       => '1-31',
		'name'       => '国际麻风节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '1-26',
		'name'       => '国际海关日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '2-2',
		'name'       => '世界湿地日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '2-7',
		'name'       => '国际声援南非日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '2-10',
		'name'       => '国际气象节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '2-14',
		'name'       => '情人节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '2-24',
		'name'       => '第三世界青年日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '2-4',
		'name'       => '世界抗癌症日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '2-21',
		'name'       => '国际母语日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '2-29',
		'name'       => '国际罕见病日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-1',
		'name'       => '国际海豹日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-3',
		'name'       => '全国爱耳日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-5',
		'name'       => '学雷锋纪念日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-8',
		'name'       => '三八妇女节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-12',
		'name'       => '植树节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-14',
		'name'       => '白色情人节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-15',
		'name'       => '消费者权益日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-17',
		'name'       => '国际航海日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-20',
		'name'       => '世界无肉日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-21',
		'name'       => '世界睡眠日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-22',
		'name'       => '世界水日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-23',
		'name'       => '世界气象日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-11',
		'name'       => '国际尊严尊敬日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-14',
		'name'       => '国际警察日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-21',
		'name'       => '世界森林日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-21',
		'name'       => '世界儿歌日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-21',
		'name'       => '国际消除种族歧视日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-24',
		'name'       => '世界防治结核病日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '3-25',
		'name'       => '耶稣受难日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '4-1',
		'name'       => '愚人节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '4-2',
		'name'       => '国际儿童图书日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '4-7',
		'name'       => '世界卫生日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '4-11',
		'name'       => '世界帕金森病日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '4-22',
		'name'       => '世界地球日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '4-23',
		'name'       => '世界读书日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '4-26',
		'name'       => '世界知识产权日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '4-16',
		'name'       => '复活节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-4',
		'name'       => '中国青年节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-3',
		'name'       => '世界哮喘日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-8',
		'name'       => '世界红十字日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-12',
		'name'       => '国际护士节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-第二个星期',
		'name'       => '母亲节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-15',
		'name'       => '国际家庭日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '05-15',
		'name'       => '防治碘缺乏病日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-17',
		'name'       => '世界电信日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-18',
		'name'       => '国际博物馆日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-15',
		'name'       => '全国助残日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-20',
		'name'       => '全国学生营养日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-20',
		'name'       => '全国母乳喂养宣传日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-22',
		'name'       => '国际生物多样性日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '5-31',
		'name'       => '世界无烟日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '五月初五',
		'name'       => '端午节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '6-6',
		'name'       => '全国爱眼日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '6-1',
		'name'       => '国际儿童节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '6-5',
		'name'       => '世界环境日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '6-11',
		'name'       => '中国文化遗产日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '6-20',
		'name'       => '世界难民日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '6-23',
		'name'       => '国际奥林匹克日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '6-25',
		'name'       => '全国土地日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '6-26',
		'name'       => '国际禁毒日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '6-26',
		'name'       => '联合国宪章日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '7-1',
		'name'       => '香港回归纪念日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '7月1号',
		'name'       => '建党节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9-3',
		'name'       => '中国人民抗日战争纪念日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '7-11',
		'name'       => '世界人口日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '8-1',
		'name'       => '八一建军节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9-8',
		'name'       => '国际扫盲日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9-10',
		'name'       => '教师节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9-10',
		'name'       => '世界预防自杀日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9-16',
		'name'       => '国际臭氧层保护日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9-18',
		'name'       => '中国国耻日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9-20',
		'name'       => '国际爱牙日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9-21',
		'name'       => '国际和平日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9-27',
		'name'       => '世界旅游日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-1',
		'name'       => '国际音乐日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-4',
		'name'       => '世界动物日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-8',
		'name'       => '全国高血压日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-9',
		'name'       => '世界邮政日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-10',
		'name'       => '世界精神卫生日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-15',
		'name'       => '国际盲人节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-16',
		'name'       => '世界粮食节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-17',
		'name'       => '国际消除贫困日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-22',
		'name'       => '世界传统医药日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-24',
		'name'       => '联合国日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10-25',
		'name'       => '人类天花绝迹日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '11-1',
		'name'       => '万圣节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '11-8',
		'name'       => '中国记者日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '11-9',
		'name'       => '消防宣传日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '11-11',
		'name'       => '光棍节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '11-14',
		'name'       => '联合国糖尿病日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '11-17',
		'name'       => '国际大学生节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '12-1',
		'name'       => '世界艾滋病日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '12-3',
		'name'       => '国际残疾人日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '12-9',
		'name'       => '世界足球日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '12-13',
		'name'       => '南京大屠杀纪念日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '12-15',
		'name'       => '世界强化免疫日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '12-20',
		'name'       => '澳门回归日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '12-21',
		'name'       => '国际篮球日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '12-24',
		'name'       => '平安夜',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '12-25',
		'name'       => '圣诞节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '12-26',
		'name'       => '毛泽东诞辰日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
];
//特殊阳历节日:a月第b个星期c
$special_gregorian_holiday = [
	[
		'time'       => '7月第一个星期六',
		'name'       => '国际合作节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9月第四个星期日',
		'name'       => '国际聋人节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10月第一个星期一',
		'name'       => '世界住房日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '10月第二个星期四',
		'name'       => '世界视觉日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '十月第二个星期三',
		'name'       => '国际减轻自然灾害日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '9月最后一周',
		'name'       => '世界海事日',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '11月第四个星期四',
		'name'       => '感恩节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '6月第三个星期日',
		'name'       => '父亲节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
];
//阴历节日
$lunar_holiday = [
	[
		'time'       => '正月初一',
		'name'       => '春节',
		'days'       => 6,
		'start_year' => 0,
		'work'       => NOT_WORK,
	],
	[
		'time'       => '五月初五',
		'name'       => '端午节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => NOT_WORK,
	],
	[
		'time'       => '八月十五',
		'name'       => '中秋节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => NOT_WORK,
	],
	[
		'time'       => '十二月三十',
		'name'       => '除夕',
		'days'       => 1,
		'start_year' => 0,
		'work'       => NOT_WORK,
	],
	[
		'time'       => '九月初九',
		'name'       => '重阳节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '七月十五',
		'name'       => '中元节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '七月初七',
		'name'       => '七夕情人节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '二月初二',
		'name'       => '龙抬头',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '腊月初八',
		'name'       => '腊八节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '腊月廿三',
		'name'       => '北方小年',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '腊月廿四',
		'name'       => '南方小年',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '正月十五',
		'name'       => '元宵节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
];
//节气节日
$solarterms_holiday = [
	[
		'time'       => '立春',
		'name'       => '立春',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '雨水',
		'name'       => '雨水',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '惊蛰',
		'name'       => '惊蛰',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '春分',
		'name'       => '春分',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '清明',
		'name'       => '清明节',
		'days'       => 1,
		'start_year' => 0,
		'work'       => NOT_WORK,
	],
	[
		'time'       => '谷雨',
		'name'       => '谷雨',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '立夏',
		'name'       => '立夏',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '小满',
		'name'       => '小满',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '芒种',
		'name'       => '芒种',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '夏至',
		'name'       => '夏至',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '小暑',
		'name'       => '小暑',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '大暑',
		'name'       => '大暑',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '立秋',
		'name'       => '立秋',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '处暑',
		'name'       => '处暑',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '白露',
		'name'       => '白露',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '秋分',
		'name'       => '秋分',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '寒露',
		'name'       => '寒露',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '霜降',
		'name'       => '霜降',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '立冬',
		'name'       => '立冬',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '小雪',
		'name'       => '小雪',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '大雪',
		'name'       => '大雪',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '冬至',
		'name'       => '冬至',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '小寒',
		'name'       => '小寒',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
	[
		'time'       => '大寒',
		'name'       => '大寒',
		'days'       => 1,
		'start_year' => 0,
		'work'       => WORK,
	],
];

return [
	'gregorian_holiday'         => $gregorian_holiday,
	'special_gregorian_holiday' => $special_gregorian_holiday,
	'lunar_holiday'             => $lunar_holiday,
	'solarterms_holiday'        => $solarterms_holiday,
];
