<?php
/**
* 时间格式:
* array(
* 	Time			=>时间,
* 	Name			=>中文名称,
* 	EnglishName		=>英文名称,
* 	IsNotWork		=>是否不工作(是否放假,有些节日不放假),
* 	Start			=>放假开始时间(-1则提前一天放假),
* 	End				=>放假结束时间(+1则延后一天放假)
* )
* 总放假天数:|Start|+|End|+1
* 
* @author zhusaidong [zhusaidong@gmail.com]
* @version 0.2.0.0
*/
const NotWork = 1;
const Work = 0;
//阳历
$GregorianCalendarHoliday = array(
	array(
		"Time"			=> "1月1日",
		"Name"			=> "中国元旦",
		"EnglishName"	=> "New Year's Day",
		"IsNotWork"		=> NotWork,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "2月2日",
		"Name"			=> "世界湿地日",
		"EnglishName"	=> "World Wetlands Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "2月14日",
		"Name"			=> "情人节",
		"EnglishName"	=> "Valentine's Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月3日",
		"Name"			=> "全国爱耳日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月5日",
		"Name"			=> "青年志愿者服务日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月8日",
		"Name"			=> "国际妇女节",
		"EnglishName"	=> "International Women' Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月9日",
		"Name"			=> "保护母亲河日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月12日",
		"Name"			=> "中国植树节",
		"EnglishName"	=> "China Arbor Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月14日",
		"Name"			=> "白色情人节",
		"EnglishName"	=> "White Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月14日",
		"Name"			=> "国际警察日",
		"EnglishName"	=> "International Policemen' Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月15日",
		"Name"			=> "世界消费者权益日",
		"EnglishName"	=> "World Consumer Right Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月21日",
		"Name"			=> "世界森林日",
		"EnglishName"	=> "World Forest Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月21日",
		"Name"			=> "世界睡眠日",
		"EnglishName"	=> "World Sleep Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月22日",
		"Name"			=> "世界水日",
		"EnglishName"	=> "World Water Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月23日",
		"Name"			=> "世界气象日",
		"EnglishName"	=> "World Meteorological Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月24日",
		"Name"			=> "世界防治结核病日",
		"EnglishName"	=> "World Tuberculosis Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "4月1日",
		"Name"			=> "愚人节",
		"EnglishName"	=> "April Fools' Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "4月5日",
		"Name"			=> "清明节",
		"EnglishName"	=> "Tomb",
		"IsNotWork"		=> NotWork,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "4月7日",
		"Name"			=> "世界卫生日",
		"EnglishName"	=> "World Health Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "4月22日",
		"Name"			=> "世界地球日",
		"EnglishName"	=> "World Earth Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "4月26日",
		"Name"			=> "世界知识产权日",
		"EnglishName"	=> "World Intellectual Property Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月1日",
		"Name"			=> "国际劳动节",
		"EnglishName"	=> "International Labour Day",
		"IsNotWork"		=> NotWork,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月3日",
		"Name"			=> "世界哮喘日",
		"EnglishName"	=> "World Asthma Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月4日",
		"Name"			=> "中国青年节",
		"EnglishName"	=> "Chinese Youth Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月8日",
		"Name"			=> "世界红十字日",
		"EnglishName"	=> "World Red",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月12日",
		"Name"			=> "国际护士节",
		"EnglishName"	=> "International Nurse Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月15日",
		"Name"			=> "国际家庭日",
		"EnglishName"	=> "International Family Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月17日",
		"Name"			=> "世界电信日",
		"EnglishName"	=> "World Telecommunications Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月20日",
		"Name"			=> "全国学生营养日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月23日",
		"Name"			=> "国际牛奶日",
		"EnglishName"	=> "International Milk Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月31日",
		"Name"			=> "世界无烟日",
		"EnglishName"	=> "World No",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "6月1日",
		"Name"			=> "国际儿童节",
		"EnglishName"	=> "International Children's Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "6月5日",
		"Name"			=> "世界环境日",
		"EnglishName"	=> "International Environment Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "6月6日",
		"Name"			=> "全国爱眼日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "6月17日",
		"Name"			=> "世界防治荒漠化和干旱日",
		"EnglishName"	=> "World Day to combat desertification",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "6月23日",
		"Name"			=> "国际奥林匹克日",
		"EnglishName"	=> "International Olympic Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "6月25日",
		"Name"			=> "全国土地日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "6月26日",
		"Name"			=> "国际禁毒日",
		"EnglishName"	=> "International Day Against Drug Abuse and Illicit Trafficking",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "7月1日",
		"Name"			=> "建党节",
		"EnglishName"	=> "Anniversary of the Founding of the Chinese Communist Party",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "7月1日",
		"Name"			=> "国际建筑日",
		"EnglishName"	=> "International Architecture Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "7月7日",
		"Name"			=> "中国人民抗日战争纪念日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "7月11日",
		"Name"			=> "世界人口日",
		"EnglishName"	=> "World Population Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "8月1日",
		"Name"			=> "建军节",
		"EnglishName"	=> "Army Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "8月12日",
		"Name"			=> "国际青年节",
		"EnglishName"	=> "International Youth Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "9月8日",
		"Name"			=> "国际扫盲日",
		"EnglishName"	=> "International Anti",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "9月10日",
		"Name"			=> "中国教师节",
		"EnglishName"	=> "Teacher's Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "9月16日",
		"Name"			=> "中国脑健康日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "9月16日",
		"Name"			=> "国际臭氧层保护日",
		"EnglishName"	=> "International Day for the Preservation of the Ozone Layer",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "9月20日",
		"Name"			=> "全国爱牙日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "9月21日",
		"Name"			=> "世界停火日",
		"EnglishName"	=> "World Cease",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "9月27日",
		"Name"			=> "世界旅游日",
		"EnglishName"	=> "World Tourism Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月1日",
		"Name"			=> "国庆节",
		"EnglishName"	=> "National Day",
		"IsNotWork"		=> NotWork,
		"Start"			=> 0,
		"End"			=> 6,
	),
	array(
		"Time"			=> "10月1日",
		"Name"			=> "国际音乐日",
		"EnglishName"	=> "International Music Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月1日",
		"Name"			=> "国际老年人日",
		"EnglishName"	=> "International Day of Older Persons",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月4日",
		"Name"			=> "世界动物日",
		"EnglishName"	=> "World Animal Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月5日",
		"Name"			=> "世界教师日",
		"EnglishName"	=> "World Teachers' Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月8日",
		"Name"			=> "全国高血压日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月9日",
		"Name"			=> "世界邮政日",
		"EnglishName"	=> "World Post Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月10日",
		"Name"			=> "世界精神卫生日",
		"EnglishName"	=> "World Mental Health Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月14日",
		"Name"			=> "世界标准日",
		"EnglishName"	=> "World Standards Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月15日",
		"Name"			=> "国际盲人节",
		"EnglishName"	=> "International Day of the Blind",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月15日",
		"Name"			=> "世界农村妇女日",
		"EnglishName"	=> "World Rural Women's Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月16日",
		"Name"			=> "世界粮食日",
		"EnglishName"	=> "World Food Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月17日",
		"Name"			=> "国际消除贫困日",
		"EnglishName"	=> "International Day for the Eradication of Poverty",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月24日",
		"Name"			=> "联合国日",
		"EnglishName"	=> "United Nations Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月24日",
		"Name"			=> "世界发展新闻日",
		"EnglishName"	=> "World Development Information Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月28日",
		"Name"			=> "中国男性健康日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月29日",
		"Name"			=> "国际生物多样性日",
		"EnglishName"	=> "International Biodiversity Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月31日",
		"Name"			=> "万圣节",
		"EnglishName"	=> "Halloween",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "11月8日",
		"Name"			=> "中国记者节",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "11月9日",
		"Name"			=> "消防宣传日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "11月14日",
		"Name"			=> "世界糖尿病日",
		"EnglishName"	=> "World Diabetes Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "11月17日",
		"Name"			=> "国际大学生节",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "11月25日",
		"Name"			=> "国际消除对妇女的暴力日",
		"EnglishName"	=> "International Day For the elimination of Violence against Women",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "12月1日",
		"Name"			=> "世界爱滋病日",
		"EnglishName"	=> "World AIDS Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "12月3日",
		"Name"			=> "世界残疾人日",
		"EnglishName"	=> "World Disabled Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "12月4日",
		"Name"			=> "全国法制宣传日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "12月9日",
		"Name"			=> "世界足球日",
		"EnglishName"	=> "World Football Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "12月25日",
		"Name"			=> "圣诞节",
		"EnglishName"	=> "Christmas Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "12月29日",
		"Name"			=> "国际生物多样性日",
		"EnglishName"	=> "International Biological Diversity Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
);
//特殊阳历
$SpecialHoliday = array(
	array(
		"Time"			=> "1月最后一个星期日",
		"Name"			=> "国际麻风节",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "3月最后一个完整周的星期一",
		"Name"			=> "中小学生安全教育日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月第二个星期日",
		"Name"			=> "母亲节",
		"EnglishName"	=> "Mother's Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "5月第三个星期日",
		"Name"			=> "全国助残日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "6月第三个星期日",
		"Name"			=> "父亲节",
		"EnglishName"	=> "Father's Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "9月第三个星期二",
		"Name"			=> "国际和平日",
		"EnglishName"	=> "International Peace Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "9月第三个星期六",
		"Name"			=> "全国国防教育日",
		"EnglishName"	=> "",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "9月第四个星期日",
		"Name"			=> "国际聋人节",
		"EnglishName"	=> "International Day of the Deaf",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月第一个星期一",
		"Name"			=> "世界住房日",
		"EnglishName"	=> "World Habitat Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月第二个星斯一",
		"Name"			=> "加拿大感恩节",
		"EnglishName"	=> "Thanksgiving Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月第二个星期三",
		"Name"			=> "国际减轻自然灾害日",
		"EnglishName"	=> "International Day for Natural Disaster Reduction",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "10月第二个星期四",
		"Name"			=> "世界爱眼日",
		"EnglishName"	=> "World Sight Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "11月最后一个星期四",
		"Name"			=> "美国感恩节",
		"EnglishName"	=> "Thanksgiving Day",
		"IsNotWork"		=> NotWork,
		"Start"			=> 0,
		"End"			=> 0,
	),
);
//阴历
$LunarCalendarHoliday = array(
	array(
		"Time"			=> "正月初一",
		"Name"			=> "春节",
		"EnglishName"	=> "the Spring Festival",
		"IsNotWork"		=> NotWork,
		"Start"			=> 0,
		"End"			=> 6,
	),
	array(
		"Time"			=> "正月十五",
		"Name"			=> "元宵节",
		"EnglishName"	=> "Lantern Festival",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "五月初五",
		"Name"			=> "端午节",
		"EnglishName"	=> "the Dragon-Boat Festival",
		"IsNotWork"		=> NotWork,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "七月初七",
		"Name"			=> "乞巧节",
		"EnglishName"	=> "Double-Seventh Day",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "八月十五",
		"Name"			=> "中秋节",
		"EnglishName"	=> "the Mid-Autumn Festival",
		"IsNotWork"		=> NotWork,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "九月初九",
		"Name"			=> "重阳节",
		"EnglishName"	=> "the Double Ninth Festival",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "腊月初八",
		"Name"			=> "腊八节",
		"EnglishName"	=> "the laba Rice Porridge Festival",
		"IsNotWork"		=> Work,
		"Start"			=> 0,
		"End"			=> 0,
	),
	array(
		"Time"			=> "十二月三十",
		"Name"			=> "除夕",
		"EnglishName"	=> "New Year's Eve",
		"IsNotWork"		=> NotWork,
		"Start"			=> 0,
		"End"			=> 0,
	),
);
